# Generated by Django 6.0.7 on 2026-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.CharField(max_length=128, verbose_name='Почта')),
                ('expire_date', models.DateField(verbose_name='Действует до:')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован?')),
                ('price', models.FloatField(verbose_name='На сумму:')),
                ('used_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('token', models.CharField(max_length=128)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('email_sended', models.BooleanField(default=False, verbose_name='Отправлен на почту?')),
            ],
        ),
    ]
