# Generated by Django 6.0.7 on 2026-08-06 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True, verbose_name='Номинал (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Номинал сертификата',
                'verbose_name_plural': 'Номиналы сертификатов',
                'ordering': ['order', 'value'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificatemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='На сумму:'),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
