# Generated by Django 5.0 on 2026-09-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0002_certificatenominal_alter_certificatemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificatenominal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
