# Generated by Django 6.0.7 on 2026-07-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Уход, который любит тебя', max_length=200)),
                ('subtitle', models.CharField(default='Скидка 20% на наши бестселлеры. Предложение ограничено!', max_length=200)),
                ('badge_text', models.CharField(default='20% OFF', help_text='Крупная цифра на баннере', max_length=50)),
                ('badge_small', models.CharField(default='OFF', help_text='Маленький текст рядом с цифрой', max_length=50)),
                ('button_text', models.CharField(blank=True, help_text='Кнопка на баннере (опционально)', max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Раскрой своё природное сияние', max_length=200)),
                ('subtitle', models.TextField(default='Уход за кожей, маникюр, педикюр и брови — всё в одном месте.', help_text='Описание под заголовком')),
                ('badge_text', models.CharField(default='✨ Новая коллекция', help_text='Маленький тег сверху', max_length=50)),
                ('offer_text', models.CharField(default='🌸 20% OFF — для новых клиентов', max_length=200)),
                ('button_text', models.CharField(default='Записаться сейчас', max_length=50)),
                ('button_link', models.CharField(default='#', help_text='Ссылка на WhatsApp/Telegram', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Фото мастера', null=True, upload_to='hero/')),
                ('stat_1_number', models.CharField(default='10K+', max_length=20)),
                ('stat_1_label', models.CharField(default='Довольных клиентов', max_length=50)),
                ('stat_2_number', models.CharField(default='4.8', max_length=20)),
                ('stat_2_label', models.CharField(default='★ Средний рейтинг', max_length=50)),
                ('stat_3_number', models.CharField(default='98%', max_length=20)),
                ('stat_3_label', models.CharField(default='Возвращаются', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герой',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', help_text='Ссылка или якорь #id', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_avatar', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Маникюр', max_length=100)),
                ('icon', models.CharField(help_text='💅 или другой эмодзи', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Гель, дизайн, уход', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше — выше)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Glowora', max_length=100)),
                ('site_logo', models.ImageField(blank=True, help_text='Загрузите логотип (прозрачный PNG)', null=True, upload_to='logo/')),
                ('phone', models.CharField(blank=True, help_text='+7 (999) 123-45-67', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Ссылка на WhatsApp', max_length=20)),
                ('telegram', models.CharField(blank=True, help_text='Ссылка на Telegram', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Метро [Станция], 5 минут пешком')),
                ('map_iframe', models.TextField(blank=True, help_text='iframe-код Яндекс.Карт')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('instagram', models.URLField(blank=True)),
                ('vk', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='© 2026 — Бьюти-студия', max_length=200)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TrustBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Красота, которая любит тебя', max_length=200)),
                ('subtitle', models.CharField(default='Скидка 20% на наши бестселлеры', max_length=200)),
                ('stat_1_number', models.CharField(default='4.8', max_length=20)),
                ('stat_1_label', models.CharField(default='Средний рейтинг', max_length=50)),
                ('stat_1_extra', models.CharField(default='★★★★★', help_text='Звёздочки', max_length=20)),
                ('stat_2_number', models.CharField(default='10K+', max_length=20)),
                ('stat_2_label', models.CharField(default='Довольных клиентов', max_length=50)),
                ('stat_3_number', models.CharField(default='98%', max_length=20)),
                ('stat_3_label', models.CharField(default='Возвращаются', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Блок доверия',
                'verbose_name_plural': 'Блок доверия',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Премиум-маникюр', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(decimal_places=0, default=2500, help_text='Текущая цена', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, help_text='Старая цена (зачёркнутая)', max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='4.8, 5.0, и т.д.', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, help_text='Количество отзывов (109)')),
                ('button_text', models.CharField(default='Запись', max_length=50)),
                ('button_link', models.CharField(default='#', help_text='Ссылка на запись', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False, help_text='Помечать как бестселлер (🔥)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='beauty_app.servicecategory')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
    ]
