# Generated by Django 5.0 on 2026-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
                ('slot_type', models.CharField(choices=[('day_off', 'Выходной день'), ('personal', 'Личные дела'), ('maintenance', 'Технический перерыв'), ('other', 'Другое')], default='day_off', max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заблокированный слот',
                'verbose_name_plural': 'Заблокированные слоты',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Например: 2026-10-15', unique=True, verbose_name='Дата выходного')),
                ('reason', models.CharField(blank=True, help_text='Например: Праздник, Отпуск мастера', max_length=100, verbose_name='Причина (необязательно)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['-date'],
            },
        ),
    ]
