# Generated by Django 5.0 on 2026-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0004_blockedslot_dayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='duration',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Длительность'),
        ),
    ]
