# Generated by Django 5.0 on 2026-09-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема поста')),
                ('description', models.TextField(blank=True, help_text='Что важно упомянуть? Какие детали?', verbose_name='Описание/контекст')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('both', 'Обе платформы')], default='telegram', max_length=20, verbose_name='Платформа')),
                ('status', models.CharField(choices=[('new', '🆕 Новая'), ('in_progress', '⚙️ В работе'), ('ready', '✅ Готова к публикации'), ('published', ' Опубликована'), ('archived', '📦 В архиве')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Идея поста',
                'verbose_name_plural': 'Идеи постов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, help_text='Например: "Вариант 1", "Часть 1 из 3", "Для Telegram"', max_length=100, verbose_name='Название варианта')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст поста')),
                ('hashtags', models.CharField(blank=True, max_length=300, verbose_name='Хештеги')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gen_posts_app.postidea', verbose_name='Идея')),
            ],
            options={
                'verbose_name': 'Контент поста',
                'verbose_name_plural': 'Контент постов',
                'ordering': ['-created_at'],
            },
        ),
    ]
