"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from environs import Env



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
env.read_env(BASE_DIR / ".env.prod")

# Quick-start development settings - unsuitable for production 
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# 1. Базовые настройки Django из .env
SECRET_KEY = env.str('SECRET_KEY')

# DEBUG должен быть булевым. В .env мы храним его как '0' или '1'
DEBUG = env.bool('DEBUG')


ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'beauty_app',
    'cert_app',
    'gen_posts_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('POSTGRES_DB'),
        'USER': env.str('POSTGRES_USER'),
        'PASSWORD': env.str('POSTGRES_PASSWORD'),
        'HOST': env.str('POSTGRES_HOST', default='db'), # 'db' - это имя сервиса в docker-compose
        'PORT': env.str('POSTGRES_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

# Часовой пояс (для Санкт-Петербурга)
TIME_ZONE = 'Europe/Moscow'

# Обязательно добавь эти настройки, если их нет:
USE_I18N = True  # Включает поддержку интернационализации
USE_L10N = True  # Включает локализацию форматов (даты, числа)
USE_TZ = True    # Включает поддержку часовых поясов

# Список поддерживаемых языков (опционально, но полезно)
LANGUAGES = [
    ('ru', 'Русский'),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Куда команда collectstatic будет собирать все файлы для продакшена
# (Nginx будет раздавать файлы именно отсюда)
STATIC_ROOT = BASE_DIR / 'static'


MEDIA_ROOT = BASE_DIR / "media"

EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')
CERT_SECRET = env.str('CERT_SECRET')
ADMIN_API_SECRET = env.str('ADMIN_API_SECRET')
WEB_PASSWORDS = env.list('WEB_PASSWORDS', subcast=str, default=[])


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'       # Пример для Яндекс Почты
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dz5011@yandex.ru'
EMAIL_HOST_PASSWORD = "vjoafohcczjunxdy"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Отправитель по умолчанию


# settings.py

MAILERS = {
    "default": {  # Конфигурация по умолчанию
        "BACKEND": EMAIL_BACKEND,
        "OPTIONS": {
            "host": "smtp.yandex.ru",
            "port": 587,
            "use_tls": True,
            "username": EMAIL_HOST_USER,
            "password": EMAIL_HOST_PASSWORD,
        },
    },
    # Здесь можно добавить другие конфигурации, например, для уведомлений
}


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin-dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Сообщения
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'error',
    messages.SUCCESS: 'success',
}


if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True